### PR TITLE
Some Fixes.

### LINKED ISSUE #76: Bug when using field in join key that is not part of the requested fields
If the join key uses a field that is not part of the requested fields, then the join fails.

join_key: "null-testmetric"

### PR DESCRIPTION
**Pull request by FlorianLautenschlager**

### CODE REVIEW

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java [hunk 1]
```diff
@@ -127,35 +126,35 @@ public void handleRequestBody(SolrQueryRequest req, SolrQueryResponse rsp) throw
...
-        //the data is needed if there are functions, or the data should be returned or
+        //the data is needed if there are functions, or the data should be returned or the data is requested as json
         boolean decompressDataAsItIsRequested = (!functions.isEmpty() || dataAsJson || dataShouldReturned);
 
         final List<SolrDocument> resultDocuments = Collections.synchronizedList(new ArrayList<>(collectedDocs.size()));
 
         collectedDocs.entrySet().parallelStream().forEach(docs -> {
             try {
+                FunctionValueMap functionValues = new FunctionValueMap(functions.sizeOfAggregations(), functions.sizeOfAnalyses(), functions.sizeOfTransformations());
+                ;
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java]: \[Checkstyle\] ERROR: Empty statement\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java [hunk 2]
```diff
@@ -213,12 +213,12 @@ private static boolean hasTransformationsOrAggregations(FunctionValueMap functio
      * @throws ParseException if bad things happen
      * @throws IOException    if bad things happen
      */
-    private void applyAnalyses(SolrQueryRequest req, Iterable<ChronixAnalysis<MetricTimeSeries>> analyses, Function<SolrDocument, String> key, long queryStart, long queryEnd, Map.Entry<String, List<SolrDocument>> docs, MetricTimeSeries timeSeries, FunctionValueMap analysisAndValues) throws ParseException, IOException {
+    private void applyAnalyses(SolrQueryRequest req, Iterable<ChronixAnalysis> analyses, JoinFunction key, long queryStart, long queryEnd, Map.Entry<String, List<SolrDocument>> docs, MetricTimeSeries timeSeries, FunctionValueMap analysisAndValues) throws ParseException, IOException {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java]: \[Checkstyle\] ERROR: More than 7 parameters \(found 8\)\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java [hunk 3]
```diff
@@ -128,12 +127,34 @@ private static void addFunction(QueryFunctions<MetricTimeSeries> result, Functio
...
+        } else if (FunctionType.isStrace(type)) {
+            addStrace(result, type, arguments);
         } else {
             LOGGER.info("{} is unknown. {} is ignored", type, type);
         }
     }
 
-    private static void addAggregation(QueryFunctions<MetricTimeSeries> result, FunctionType type, String[] arguments) {
+    private static void addStrace(QueryFunctions result, FunctionType type, String[] arguments) {
+        switch (type) {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java]: \[Checkstyle\] ERROR: switch without "default" clause\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java [hunk 4]
```diff
@@ -128,12 +127,34 @@ private static void addFunction(QueryFunctions<MetricTimeSeries> result, Functio
...
+            case SPLIT:
+                result.addTransformation(new Split());
+                break;
+        }
+    }
+
+    private static void addLsof(QueryFunctions result, FunctionType type, String[] arguments) {
+        switch (type) {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java]: \[Checkstyle\] ERROR: switch without "default" clause\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/SolrDocumentBuilder.java [hunk 5]
```diff
@@ -156,6 +191,91 @@ private static void addAnalysesAndResults(FunctionValueMap functionValueMap, Sol
...
+        List<List<Lsof>> values = new ArrayList<>();
+        for (SolrDocument doc : documents) {
+            LsofTimeSeries ts = convertLSOF(doc, queryStart, queryEnd, decompress);
+
+            //only if we decompress the data.
+            if (decompress) {
+                //Performance optimization. Avoiding fine grained growing.
+                if (timestamps == null) {
+                    int size = ts.size();
+                    if (size < 1000) {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/SolrDocumentBuilder.java]: \[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/SolrDocumentBuilder.java [hunk 6]
```diff
@@ -156,6 +191,91 @@ private static void addAnalysesAndResults(FunctionValueMap functionValueMap, Sol
...
+        List<Strace> values = new ArrayList<>();
+        for (SolrDocument doc : documents) {
+            StraceTimeSeries ts = convertStrace(doc, queryStart, queryEnd, decompress);
+
+            //only if we decompress the data.
+            if (decompress) {
+                //Performance optimization. Avoiding fine grained growing.
+                if (timestamps == null) {
+                    int size = ts.size();
+                    if (size < 1000) {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/SolrDocumentBuilder.java]: \[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Avg.java [hunk 7]
```diff
@@ -29,22 +30,16 @@
...
-            throw new IllegalArgumentException("Avg aggregation needs at least one time series");
-        }
-        //Took the first time series
-        MetricTimeSeries timeSeries = args[0];
+    public void execute(MetricTimeSeries timeSeries, FunctionValueMap analysisAndValues) {
 
         //If it is empty, we return NaN
         if (timeSeries.size() <= 0) {
-            return Double.NaN;
+            analysisAndValues.add(this,Double.NaN);
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Avg.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java [hunk 8]
```diff
@@ -31,22 +32,15 @@
...
-            throw new IllegalArgumentException("Difference function needs at least one time series");
-        }
-        //Took the first time series
-        MetricTimeSeries timeSeries = args[0];
-
+    public void execute(MetricTimeSeries timeSeries, FunctionValueMap analysisAndValues) {
         //If it is empty, we return NaN
         if (timeSeries.size() <= 0) {
-            return Double.NaN;
+            analysisAndValues.add(this,Double.NaN);
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java [hunk 9]
```diff
@@ -55,8 +49,8 @@ public double execute(MetricTimeSeries... args) {
         double firstValue = timeSeries.getValue(0);
         double lastValue = timeSeries.getValue(timeSeries.size() - 1);
 
-        //return the difference
-        return Math.abs(firstValue - lastValue);
+        analysisAndValues.add(this,Math.abs(firstValue - lastValue));
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/analyses/FastDtw.java [hunk 10]
```diff
@@ -52,18 +54,17 @@ public FastDtw(String subquery, int searchRadius, double maxNormalizedWarpingCos
...
         //We have to build a multivariate time series
-        MultivariateTimeSeries origin = buildMultiVariateTimeSeries(args[0]);
-        MultivariateTimeSeries other = buildMultiVariateTimeSeries(args[1]);
+        MultivariateTimeSeries origin = buildMultiVariateTimeSeries(timeSeriesPair.first());
+        MultivariateTimeSeries other = buildMultiVariateTimeSeries(timeSeriesPair.second());
         //Call the fast dtw library
         TimeWarpInfo result = FastDTW.getWarpInfoBetween(origin, other, searchRadius, distanceFunction);
         //Check the result. If it lower equals the threshold, we can return the other time series
-        return result.getNormalizedDistance() <= maxNormalizedWarpingCost;
+        //TODO: Add the result to the time series
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/analyses/FastDtw.java]: \[Checkstyle\] ERROR: Comment matches to\-do format 'TODO:'\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/analyses/Outlier.java [hunk 11]
```diff
@@ -30,23 +31,20 @@
...
-        if (args.length <= 0) {
-            throw new IllegalArgumentException("Trend detection needs at least one time series");
-        }
-
-        MetricTimeSeries timeSeries = args[0];
+    public void execute(MetricTimeSeries timeSeries, FunctionValueMap analysisAndValues) {
 
         if (timeSeries.isEmpty()) {
-            return false;
+            //TODO: Add result
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/analyses/Outlier.java]: \[Checkstyle\] ERROR: Comment matches to\-do format 'TODO:'\.

File: chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java [hunk 12]
```diff
@@ -0,0 +1,88 @@
...
+
+    @Override
+    public void init(PluginInfo info) {
+
+    }
+
+    @Override
+    public void handleRequestBody(SolrQueryRequest req, SolrQueryResponse rsp) throws Exception {
+        //Check: https://cwiki.apache.org/confluence/display/solr/Uploading+Data+with+Index+Handlers
+        //TODO: Handle the request
```
Comment (sputnikci) [inline chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java]: \[Checkstyle\] ERROR: Comment matches to\-do format 'TODO:'\.

File: chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+
+        //1) Parse input: Graphite line protocol, opentsdb, influxdb
+
+        LOGGER.info("I was called");
+        String result = IOUtils.toString(req.getContentStreams().iterator().next().getStream(), "UTF-8");
+        LOGGER.info("Content is: {}", result);
+
+        //2) Converter to time series
+        MetricTimeSeries ts = new MetricTimeSeries.Builder("cpu_load_short")
+                .attribute("host","server02")
```
Comment (sputnikci) [inline chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java [hunk 14]
```diff
@@ -0,0 +1,88 @@
...
+                .attribute("region","us-west")
```
Comment (sputnikci) [inline chronix-server-ingestion-handler/src/main/java/de/qaware/chronix/solr/ingestion/ChronixIngestionHandler.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java [hunk 15]
```diff
@@ -213,12 +212,12 @@ private static boolean hasTransformationsOrAggregations(FunctionValueMap functio
...
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/AnalysisHandler.java]: \[Checkstyle\] ERROR: More than 7 parameters \(found 8\)\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java (hunk 3 above)
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java]: \[Checkstyle\] ERROR: switch without "default" clause\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java (hunk 4 above)
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java]: \[Checkstyle\] ERROR: switch without "default" clause\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java [hunk 16]
```diff
@@ -203,7 +227,7 @@ private static void addAnalysis(QueryFunctions<MetricTimeSeries> result, Functio
         }
     }
 
-    private static void addTransformation(QueryFunctions<MetricTimeSeries> result, FunctionType type, String[] arguments) {
+    private static void addTransformation(QueryFunctions result, FunctionType type, String[] arguments) {
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/QueryEvaluator.java]: \[Checkstyle\] ERROR: NCSS for this method is 51 \(max allowed is 50\)\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Avg.java [hunk 17]
```diff
@@ -29,22 +30,16 @@
...
-            throw new IllegalArgumentException("Avg aggregation needs at least one time series");
-        }
-        //Took the first time series
-        MetricTimeSeries timeSeries = args[0];
+    public void execute(MetricTimeSeries timeSeries, FunctionValueMap functionValueMap) {
 
         //If it is empty, we return NaN
         if (timeSeries.size() <= 0) {
-            return Double.NaN;
+            functionValueMap.add(this,Double.NaN);
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Avg.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java [hunk 18]
```diff
@@ -26,27 +27,20 @@
...
-            throw new IllegalArgumentException("Difference function needs at least one time series");
-        }
-        //Took the first time series
-        MetricTimeSeries timeSeries = args[0];
-
+    public void execute(MetricTimeSeries timeSeries, FunctionValueMap functionValueMap) {
         //If it is empty, we return NaN
         if (timeSeries.size() <= 0) {
-            return Double.NaN;
+            functionValueMap.add(this,Double.NaN);
```
Comment (sputnikci) [inline chronix-server-query-handler/src/main/java/de/qaware/chronix/solr/query/analysis/functions/aggregations/Difference.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.
